#ifndef TMSNEUROFEEDBACK_GLOBAL_H
#define TMSNEUROFEEDBACK_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TMSNEUROFEEDBACK_LIBRARY)
#  define TMSNEUROFEEDBACKSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TMSNEUROFEEDBACKSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TMSNEUROFEEDBACK_GLOBAL_H
