#ifndef EXAMPLESIGNAL_GLOBAL_H
#define EXAMPLESIGNAL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(EXAMPLESIGNAL_LIBRARY)
#  define EXAMPLESIGNALSHARED_EXPORT Q_DECL_EXPORT
#else
#  define EXAMPLESIGNALSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // EXAMPLESIGNAL_GLOBAL_H
